### ISSUE TITLE
iOS WiFi is always reported as available.

### ISSUE THREAD

**Issue by lukya** [jamesmontemagno/ConnectivityPlugin#104] opened 2017-09-27 12:51 UTC
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: iPhone 6 iOS 11.0, iPhone 6S iOS 10.3.2 (and multiple other 9.x/10.x versions) 
Simulator Tested On: NA
Version of VS: 7.1.5 (build 2) / 7.0.1 (build 24)
Version of Xamarin: NA
Versions of other things you are using: Xcode 8 & 9

### Steps to reproduce the Behavior

1. Turn off WiFi or Disconnect from WiFi network (note iOS 11 changes : https://support.apple.com/en-us/HT208086 is not the issue here)

2. Check for WiFi availability, as mentioned in the [documentation](https://jamesmontemagno.github.io/ConnectivityPlugin/CheckingConnectivity.html)

### Expected Behavior

WiFi should be reported as unavailable.

### Actual Behavior

WiFi should be reported as available.

### Code snippet

    if(CrossConnectivity.Current.ConnectionTypes.Contains(ConnectionType.WiFi)))
    {
        // WiFi is available.
    }

**Comment by jamesmontemagno** [comment] 2017-09-27 15:02
Fixed in latest beta. Duplicate of #87

**Closed as completed by jamesmontemagno** 2017-09-27 15:02 UTC
