### ISSUE TITLE
ConnectivityChangedEventHandler doesn't fire when switching between two WiFi networks

### ISSUE THREAD

**Issue by plamenkoyovchev** [jamesmontemagno/ConnectivityPlugin#171] opened 2019-07-03 13:37 UTC
When I'm switching the connection from one Wifi network ot another Wifi network the ConnectivityChangedEventHandler doesn't fire

## Bug Information

Version Number of Plugin: 3.2.0
Device Tested On: Xiaomi Mi A2 Lite
Version of VS: Visiual Studio 2019 - 16.1.4
Version of Xamarin: 4.0

### Steps to reproduce the Behavior
Switch couple of times between two WiFi networks without turning off the WiFi, just switch between two WiFis
### Expected Behavior
To fire ConnectivityChangedEventHandler  every time
### Actual Behavior
ConnectivityChangedEventHandler fired only once
### Code snippet

```
public OverviewPage()
{
    CrossConnectivity.Current.ConnectivityChanged += async (obj, e) => await Current_ConnectivityChangedAsync(obj, e);
}

private async Task Current_ConnectivityChangedAsync(object sender, ConnectivityChangedEventArgs e)
{
   if(e.IsConnected)
   {
       // Do work
    }
}
```

### Notes 

The behavior of Xamarin.Essentials.Connectivity is the same

**Comment by jamesmontemagno** [comment] 2019-07-21 08:41
You could try: ConnectivityTypeChangedEventArgs 

However it may not trigger at all because connectivity really hasn't changed in the eye of the device.

**Comment by jamesmontemagno** [comment] 2019-10-07 01:39
Closing as this is expected behavior as the connection hasn't changed as far as internet goes.

**Closed as completed by jamesmontemagno** 2019-10-07 01:39 UTC
