### ISSUE TITLE
iOS - CrossConnectivity.Current.ConnectivityChanged is not triggered

### ISSUE THREAD

**Issue by mjeronimoa** [jamesmontemagno/ConnectivityPlugin#67] opened 2017-05-29 13:51 UTC
On iOS (iPhone and iPad), when changing from a wifi network with **no Internet** access to a wifi network with **Internet** access, the event ConnectivityChanged is not triggered.
If the change is done in the opposite order (Internet access to no Internet access), this time the event is triggered.
iOS devices run out of SIM card or other connection method.
Tested it on Android and it works as expected.

## Bug Information

Version Number of Plugin: 3.0
Device Tested On: iPad Pro 10.2 /iPhone 6 Plus 10.2.1
Version of VS: VS 2015
Version of Xamarin: 4.2.2.11
Version of Xamarin.iOS: 10.3.1.8

### Steps to reproduce the Behavior
2 different wifi networks are needed, one of them with Internet access and the other one with no Internet access (an Android phone without SIM card is used as Access Point)

- Start the app connected to the network with Internet access.
- Change in the settings the network to the one without connection

### Actual Behavior
The event is not triggered after changing to the network without Internet connection

### Expected Behavior
The event is triggered after changing to the network without Internet connection

I know it is a really specific case, but it is something we faced while doing some testing one day the network was not stable at all.
Thanks for your time and please, tell me if I can help somehow.

**Comment by Suriman** [comment] 2017-07-18 08:16
Me too!.

**Comment by shrikantbmali** [comment] 2017-07-20 11:58
Me too, on Android, not sure on iOS?

**Comment by jamesmontemagno** [comment] 2017-08-11 19:21
Well in this instance it is connected to WiFi and to the OS it means that it has connectivity. In both instances the IsConnected would return true, when it changes networks it still thinks it is connected so it wouldn't trigger the event. You could use the reachability test to see if you can ping an IP.

Closing as this is by design and what the devices are reporting back.

**Closed as completed by jamesmontemagno** 2017-08-11 19:21 UTC
