### ISSUE TITLE
Issue with Xam.Plugin.Connectivity - ConnectivityChanged event

### ISSUE THREAD

**Issue by crazynitha** [jamesmontemagno/ConnectivityPlugin#161] opened 2018-09-03 19:15 UTC
In my Xamarin forms application, I am using **Xam.Plugin.Connectivity Plugin** for handling Network states( Offline & Online condition). In the app I need to display a banner in the application in case there is no network connectivity. For implementing this I am using the below event from **Xam.Plugin.Connectivity** Plugin.

`CrossConnectivity.Current.ConnectivityChanged += Current_ConnectivityChanged;`

**It is working / firing the events in all the usual cases like.**

Wifi connects / disconnects
3G/4G connects / disconnects

**But there is an issue with the below scenario (steps to reproduce).**

1. Open the application
2. Keep it idle for few hours.
3. Let the device to sleep.
4. After few hours it will call the ConnectivityChanged event with IsConnected = false (ie n/w state changes to not connected)
5. Let’s the device awake.
6. Observe the ConnectivityChanged event in the app.
7. It won’t fire the connection changed event.
8. If you try to enable or disable the network at this point. It will start firing the event.

**What I have tried**

1. I have tried registering the event and un register it in OnStart ,OnSleep , OnResume events
2. Also, I tried the same in app level page life cycle events

Please find the sample app to reproduce the [issue.](https://drive.google.com/file/d/1aEpNLEWqzAmJClOw8hLCzJTeKknJ4Xwi/view)

**Note: I have tried the same in Xamarin.Essentials library but the result is same.**

**Bug Information**

Version Number of Plugin: 3.2.0 & 4.0.0.190-beta
Device Tested On: Zebra TC25 Lite, Zebra TC50, Samsung Galaxy S6, Moto G5 Plus, Nexus 6 
Simulator Tested On: Tested on real device 
Version of VS: VS Professional 2017 with latest update 
Version of Xamarin: 3.1.0.697729 (Forms)

**Comment by jamesmontemagno** [comment] 2018-09-04 16:19
Is your app in the background?

Best practices are for you to unregister your events onsleep and re-register onresume as the device may enter deep sleep and not fire specific events.

We do register the broadcast receiver so it should be receiving them.


Is this device plugged in? What is the IsConnected state if you try to get it manually?

**Comment by crazynitha** [comment] 2018-09-05 06:12
@jamesmontemagno As I told, I have tried registering and unregistered the event in onsleep and onresume. But the issue is still present. 

app in the background? The situation is, open the **app and let the device to sleep**. That means  I am not pushing the app to background. I doubt device may doing that when it is idle for quite long time.

Is this device plugged in? The device was not plugged in, it was running on the battery power.

` CrossConnectivity.Current.IsConnected` is returning the correct value (ie, IsConnected = true) while opening the app again. But the issue I am facing is with the  `CrossConnectivity.Current.ConnectivityChanged += Current_ConnectivityChanged;` this event is not firing for the first time. Since I am handling the visibility of my "No Network Label" inside this event. It won't fire and it will show no network (Previous status)even if the network present.

In this point if you enable / disable the data connection. It will again work as expected. 

I have asked the same question in [Xamarin Essentials](https://github.com/xamarin/Essentials/issues/498) as well. There also I am getting the same issue.

**Comment by jamesmontemagno** [comment] 2018-09-05 18:08
Seems like your work around is just to manually re-trigger your event to update the UI when your app opens since it return the correct value then....

I just want to make sure i have the steps correct.

1.) Launch App
2.) Leave it unplugged on desk and app in foreground
3.) Eventually devices goes to sleep and eventually you get a disconnected from internet event
4.) After some time wake up device and check state of network...

Are you on Wifi? Cellular?

**Comment by crazynitha** [comment] 2018-09-05 18:40
I tried it on Cellular Data. I haven't tried on wifi. 

The steps you have mentioned above are correct. At step 4  state / IsConnected is returning the correct value. But the issue is  **ConnectivityChanged** event. It is not firing. Since It is not firing I cannot change the visibility of my "Network / No Network" stackloayout.  

As an alternative i tried reading the value and set the visibility of the control during OnResume. In that case, If I turn off the mobile data after resume the event not fire. 

Both the case "**Event Firing Issue only appears during the first time after coming from sleep**". after that it is working fine.

**Regarding the work around you mentioned** 
How I can manually re trigger the event? Do I need to do the same from my side or is it a change from your end?

Could you please provide some sample code?

  Note : The issue is only present, when the device got sleep automatically and the we try to come back the app after 3-4 hours.

**Comment by crazynitha** [comment] 2018-09-07 13:38
@jamesmontemagno : Any updates regarding this issue?

**Comment by jamesmontemagno** [comment] 2018-09-07 20:35
From my findings it really looks like what we have here is how the Android operating system works. I really wasn't able to reproduce the issue although I am sure there is a possibility that it is happening on your end.

By connecting to adb we can easily simulate turning on/off data:

```
adb shell svc data enable
adb shell svc data disable
```

If you boot up an emulator Android 6+ and do this with app in foreground or when the power button selected so the OnSleep gets called we still get the updates.

Now if you put you do the following we can "almost" reproduce this:

Launch app with network enabled first. then call the following:
```
adb shell svc data disable
// ui updates as disabled
adb shell dumpsys deviceidle enable
adb shell dumpsys deviceidle force-idle
// wait for screen to go out
adb shell svc data enable
```

You will no longer get any network events so this wont be triggered at all because you are in doze mode, and this is expected. Now, let's get out of doze mode and turn on the phone again with the power button:

```
adb shell dumpsys deviceidle unforce
```

Now the UI will say disconnected because that was it's state before entering doze, however the device will say that internet is connected. Now, the device is still coming out of doze most likely and re-registering all broadcast receivers. I waited about 10 seconds or so and I got an update that internet was reconnected as it was fully out of doze.

This seems to mostly be a side effect of how Android itself works where it turns back on network and then comes out of doze mode and re-hydrates the app and all of the broadcast receivers.

My recommendation is to ensure that you subscribe and unsubscribe when the app is OnResume/OnSleep or on a page OnAppearing/OnDissappearing. You should also set the UI to the state that you want OnResume/OnAppearing as there is a possibility that Doze has set in.

We can only subscribe to notifications and raise them to you when we get them. If Android doesn't fire them to use then we can't possibly raise the event. I will document this a bit better for Essentials and here, but I don't really think there is anything we can do here.

**Comment by Redth** [comment] 2018-09-08 11:55
Nice digging @jamesmontemagno !  Might it also make sense to just check the connectivity state when your app resumes if you really need to know the state that badly instead of exclusively waiting for the event to (maybe) fire?

**Comment by jamesmontemagno** [comment] 2018-09-08 18:49
Yeah, that is my thought too. I don't think there is really anything we can do as the events continue to pick up. Just a side effect of the OS itself.

**Comment by jamesmontemagno** [comment] 2018-09-18 22:02
Closing this as it is out of our hands from my testing.

**Closed as completed by jamesmontemagno** 2018-09-18 22:02 UTC
